/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2018-03-30 05:30:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.administration;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class createUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fmethod_005fid_005fcommandName_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fid_005fdata_002dlive_002dsearch_005fclass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005foptions_0026_005fitems_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fmethod_005fid_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fid_005fdata_002dlive_002dsearch_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005foptions_0026_005fitems_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fmethod_005fid_005fcommandName_005faction.release();
    _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fid_005fdata_002dlive_002dsearch_005fclass.release();
    _005fjspx_005ftagPool_005fform_005foptions_0026_005fitems_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("    \r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("\t<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("\t<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("\t-->\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t.lockY{\r\n");
      out.write("\t\tbackground-color: #cd5c5c;\r\n");
      out.write("\t\tborder-color: #cd5c5c;\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.lockY:active, .lockY.active, .lockY.active:focus, \r\n");
      out.write("\t\t.lockY:active:focus, .lockY:active:hover, .lockY.dropdown-toggle:active:hover ,.lockY:hover {\r\n");
      out.write("\t\t    background-color: #df9898 !important;\r\n");
      out.write("\t\t    border-color: #df9898;\r\n");
      out.write("\t\t    color:white;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.error{\r\n");
      out.write("\t\t\tcolor:red;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.disableY{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</style>\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/css/bootstrap-select.min.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body >\r\n");
      out.write("  <p> \r\n");
      out.write("  <button type=\"button\" class=\"btn btn-success btn-info btn-scroll btn-scroll-left ti-user\" id=\"showbutton\"\r\n");
      out.write("  \t  onclick=\"newCreate();\"><span>Create New User</span>\r\n");
      out.write("\t</button>\r\n");
      out.write("  </p>\r\n");
      out.write("  <div class=\"row margin-left-30\" id=\"tableHide\">\r\n");
      out.write("\t\t\r\n");
      out.write("       \r\n");
      out.write("        <div class=\"col-md-11 panel panel-white\" >\r\n");
      out.write("         \r\n");
      out.write("        <div class=\"table-responsive margin-top-10 margin-bottom-30\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"input-group col-md-12\">\r\n");
      out.write("\t\t\t<p><span class=\"input-icon input-icon-right\">\r\n");
      out.write("\t\t\t<input type=\"search\" placeholder=\"Search\" id=\"search\" class=\"form-control\">\r\n");
      out.write("\t\t\t<i class=\"ti-search\"></i> </span></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("     <table id=\"mytable\" class=\"table table-bordred table-striped table-search\">\r\n");
      out.write("                   \r\n");
      out.write("                   <thead>                                    \r\n");
      out.write("                   <th>User ID</th>\r\n");
      out.write("                    <th> Name of User</th>          \r\n");
      out.write("                     <th>Role Name</th>\r\n");
      out.write("                     <th>Post Name</th>\r\n");
      out.write("                    \r\n");
      out.write("                      <th>Edit</th> \r\n");
      out.write("                       <th>Block/ UnBlock</th>\r\n");
      out.write("                      <th>Reset Password</th>                    \r\n");
      out.write("                      \r\n");
      out.write("                   </thead>\r\n");
      out.write("    <tbody>\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("  \r\n");
      out.write("   </tbody>\r\n");
      out.write("        \r\n");
      out.write("</table>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"createNew\" style=\"display: none\" class=\"Ajaxcalls\">\r\n");
      out.write("\t <input type=\"hidden\"  id=\"editlength\" value='1' />\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \t ");
      if (_jspx_meth_form_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"modal fade\" id=\"delete\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"edit\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\"><span class=\"glyphicon glyphicon-remove\" aria-hidden=\"true\"></span></button>\r\n");
      out.write("        <h4 class=\"modal-title custom_align\" id=\"Heading\"><span class=\"blocking\"></span> this User</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("          <div class=\"modal-body bg-white\">\r\n");
      out.write("       \r\n");
      out.write("       <div class=\"alert alert-danger\"><span class=\"glyphicon glyphicon-warning-sign\"></span>\r\n");
      out.write("        Are you sure you want to <span class=\"blocking\"></span> user <mark id=\"blockUser\"></mark>?</div>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("      </div>\r\n");
      out.write("        <div class=\"modal-footer \">\r\n");
      out.write("        <a id=\"delateUrl\"><button type=\"button\" class=\"btn btn-success\" ><span class=\"glyphicon glyphicon-ok-sign\"></span> Yes</button></a>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\"><span class=\"glyphicon glyphicon-remove\"></span> No</button>\r\n");
      out.write("      </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    <!-- /.modal-content --> \r\n");
      out.write("  </div>\r\n");
      out.write("      <!-- /.modal-dialog --> \r\n");
      out.write("    </div> \r\n");
      out.write("    \r\n");
      out.write("    <div id=\"resetNew\" style=\"display: none\">\r\n");
      out.write("\t <input type=\"hidden\"  id=\"editlength\" value='1' />\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \t ");
      if (_jspx_meth_form_005fform_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- end: JavaScript Event Handlers for this page -->\r\n");
      out.write("\t\t<script src=\"http://code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"resources/js/sha256.js\"></script>\r\n");
      out.write("\t\t<script src=\"resources/js/tablesearch.js\"></script>\r\n");
      out.write("\t\t <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/js/bootstrap-select.min.js\"></script>\r\n");
      out.write("\t\t <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->\r\n");
      out.write("\t\t<script src=\"vendor/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("\t\t<script src=\"vendor/ckeditor/adapters/jquery.js\"></script>\r\n");
      out.write("\t\t<script src=\"vendor/jquery-validation/jquery.validate.min.js\"></script>\r\n");
      out.write("\t\t<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction newCreate(){\r\n");
      out.write("\t\t\t$('#createNew').show();\r\n");
      out.write("\t\t\t$('#resetNew').hide();\r\n");
      out.write("\t\t\t$('#tableHide,#showbutton').hide();\r\n");
      out.write("\t\t\t$('.passwordHide').show();\r\n");
      out.write("\t\t\t$('.nameChange').html(\"Register <i class='fa fa-arrow-circle-right'></i>\").removeClass(\"btn-warning\").addClass(\"btn-primary\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction cancleCreate(){\r\n");
      out.write("\t\t\tlocation.reload();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction callEditAjaxRequest(userId){\r\n");
      out.write("\t\t    $('#changer').val(\"1\");\r\n");
      out.write("\t\t    $('#serial_no').val(userId);\r\n");
      out.write("\t\t    $('.passwordHide').hide();\r\n");
      out.write("\t\t    \t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:'GET',\r\n");
      out.write("\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajaxController/editusers/'+userId+'.htm',\r\n");
      out.write("\t\t\t\t\t dataType: 'json',\r\n");
      out.write("\t\t\t\t\t beforeSend: function(){\r\n");
      out.write("\t\t\t\t\t\t        $('#divLoading').show();\r\n");
      out.write("\t\t\t\t\t\t         document.getElementsByClassName(\"Ajaxcalls\")[0].style.filter = \"blur(3px)\";\r\n");
      out.write("\t\t\t\t\t\t    },\r\n");
      out.write("\t\t\t\t\t\tcomplete: function(){\r\n");
      out.write("\t\t\t\t\t\t        $('#divLoading').hide();\r\n");
      out.write("\t\t\t\t\t\t         document.getElementsByClassName(\"Ajaxcalls\")[0].style.filter = \"blur(0px)\";\r\n");
      out.write("\t\t\t\t\t\t    },\r\n");
      out.write("\t\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\t $.each(data, function(index, op) {\r\n");
      out.write("\t\t\t\t\t\t\t \t$('#serial_no').val(op.USER_SERIAL_NO);\r\n");
      out.write("\t\t\t\t\t\t\t \t$('#role_id').val(op.ROLE_ID);\r\n");
      out.write("\t\t\t\t\t\t\t \t$('#post_id').html(\"<option value=\"+op.POST_ID+\">\"+op.POST_NAME+\"</option>\");\r\n");
      out.write("\t\t\t\t\t\t\t \t$('#firstname').val(op.USER_LOGIN_NAME);\r\n");
      out.write("\t\t\t\t\t\t\t \t$('#username').val(op.USER_NAME);\r\n");
      out.write("\t\t\t\t\t\t\t \t\r\n");
      out.write("\t\t\t\t\t\t\t \t$('#role_id').selectpicker('refresh');\r\n");
      out.write("\t\t\t\t\t\t\t \t$('#post_id').selectpicker('refresh');\r\n");
      out.write("\t\t\t\t\t        });\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\t\t\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("\t\t\t$('#resetNew').hide();\r\n");
      out.write("\t\t\t$('#createNew').show();\r\n");
      out.write("\t\t\t$('#tableHide,#showbutton').hide();\r\n");
      out.write("\t\t\t$('.nameChange').html(\"Update <i class='fa fa-arrow-circle-right'></i>\").addClass(\"btn-warning\");\t\t\t\r\n");
      out.write("\t\t  }\r\n");
      out.write("    \r\n");
      out.write("\t\t\tfunction callDelateRequest(id,name,lock){\r\n");
      out.write("\t\t\t\tif(lock === 'Y'){\r\n");
      out.write("\t\t\t\t$('.blocking').text(\"Un Block\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t$('.blocking').text(\"Block\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$('#blockUser').text(name);\r\n");
      out.write("\t\t\t\t$(\"#delateUrl\").attr(\"href\", \"createUsers/block/\"+id+\"/\"+lock+\".htm\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("    \t$(function() {\r\n");
      out.write("    \talert(pageContext.request.contextPath);\r\n");
      out.write("    \t\t$('.disableY').prop('disabled', true);\r\n");
      out.write("    \t\t$('.lockY').removeClass( \"btn-light-blue\" );\r\n");
      out.write("\t\t\t$('#role_id').on('change', function(){\r\n");
      out.write("\t\t\tvar selected = $(this).find(\"option:selected\").val();   \t   \t\t \r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'GET',\r\n");
      out.write("\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajaxController/postsList/'+selected+'.htm',\t\r\n");
      out.write("\t\t\t\t beforeSend: function(){\r\n");
      out.write("\t\t\t\t\t\t        $('#divLoading').show();\r\n");
      out.write("\t\t\t\t\t\t    },\r\n");
      out.write("\t\t\t\t\t\tcomplete: function(){\r\n");
      out.write("\t\t\t\t\t\t        $('#divLoading').hide();\r\n");
      out.write("\t\t\t\t\t\t    },\t\t\t\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t$('#post_id').html(data);\r\n");
      out.write("\t\t\t\t\t$('#post_id').selectpicker('refresh');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction callResetRequest(userId, name){\r\n");
      out.write("\t\t\t$('#resetUserName').html(\"<b>\"+name+\"</b>\");\r\n");
      out.write("\t\t\t$('#reset_serial_no').val(userId);\r\n");
      out.write("\t\t\t$('#resetNew').show();\r\n");
      out.write("\t\t\t$('#createNew').hide();\r\n");
      out.write("\t\t\t\t$('#tableHide,#showbutton').hide();\r\n");
      out.write("\t\t\t\t$('.nameChange').html(\"Reset <i class='fa fa-arrow-circle-right'></i>\").addClass(\"btn-warning\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#formCheckPassword\").validate({\r\n");
      out.write("           rules: {         \r\n");
      out.write("           \t firstname: {\r\n");
      out.write("           \t required: true,\r\n");
      out.write("           \t },\r\n");
      out.write("           \t username: {\r\n");
      out.write("           \t \trequired: true,\r\n");
      out.write("           \t },\r\n");
      out.write("               password: { \r\n");
      out.write("                 required: true,\r\n");
      out.write("                    minlength: 6\r\n");
      out.write("                    \r\n");
      out.write("               } , \r\n");
      out.write("                   password_again: { \r\n");
      out.write("                    required: true,\r\n");
      out.write("                    equalTo: \"#password\",\r\n");
      out.write("                     minlength: 6                     \r\n");
      out.write("               }\r\n");
      out.write("           },          \t\t\r\n");
      out.write("\t\t   messages:{\r\n");
      out.write("\t\t     \tusername: { \r\n");
      out.write("\t\t                 required:\"Username is required\"\r\n");
      out.write("\t\t               },\r\n");
      out.write("\t\t         password: { \r\n");
      out.write("\t\t                 required:\"Password is required\"\r\n");
      out.write("\t\t               },\r\n");
      out.write("\t\t         firstname: { \r\n");
      out.write("\t\t                 required:\"Firstname is required\"\r\n");
      out.write("\t\t               },\r\n");
      out.write("\t\t         password_again: {\r\n");
      out.write("\t\t         \trequired:\"Confirm Password is required\"\r\n");
      out.write("\t\t         }\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t     \r\n");
      out.write("\t      });\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t  $(\"#formCheck\").validate({\r\n");
      out.write("           rules: {    \t\t\r\n");
      out.write("\t           \tmaster_password :{\r\n");
      out.write("\t           \t  required: true,\r\n");
      out.write("\t           \t},\r\n");
      out.write("\t            reset_password: { \r\n");
      out.write("\t              required: true,\r\n");
      out.write("\t              minlength: 2\r\n");
      out.write("\r\n");
      out.write("\t            } , \r\n");
      out.write("\t            re_newpassword: { \r\n");
      out.write("\t               required: true,\r\n");
      out.write("\t               equalTo: \"#reset_password\",\r\n");
      out.write("\t               minlength: 2       \r\n");
      out.write("\t           }\r\n");
      out.write("           },\r\n");
      out.write("           \t\t\r\n");
      out.write("    \t\t messages:{\r\n");
      out.write("\t\t         master_password: { \r\n");
      out.write("\t\t                 required:\"Old Password is required\"\r\n");
      out.write("\t\t               },\r\n");
      out.write("\t\t         reset_password: { \r\n");
      out.write("\t\t                 required:\"New Password is required\"\r\n");
      out.write("\t\t               },\r\n");
      out.write("\t\t         re_newpassword: { \r\n");
      out.write("\t\t                 required:\"Confirm New Password is required\"\r\n");
      out.write("\t\t               },\r\n");
      out.write("    \r\n");
      out.write("     \t\t}\r\n");
      out.write("     \r\n");
      out.write("\t      });\t\r\n");
      out.write("\t      \r\n");
      out.write("\t      function selectValidate(){\t    \r\n");
      out.write("\t\t\t\t\tvar req = $('#post_id').val();\r\n");
      out.write("\t\t\t\t\tvar role = $('#role_id').val();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t if($('#password_again').val() != \"\"){\r\n");
      out.write("\t\t\t\t\t\t\t$('#password').val(Sha256.hash($('#password').val()));\r\n");
      out.write("\t\t\t\t\t\t\t$('#password_again').val(Sha256.hash($('#password_again').val()));\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif (role === \"S\" || role ===0 || role==\"S\" || role==0){\r\n");
      out.write("\t\t\t\t\t\t\tif($('#roleerror').length){\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$( \"#role_id\" ).after( \"<span class='error' id='roleerror'>Role Name is required</span>\" );\r\n");
      out.write("\t\t\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif (req === \"S\" || req ===0 || req==\"S\" || req==0){\r\n");
      out.write("\t\t\t\t\t\t\tif($('#posterror').length){\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t$( \"#post_id\" ).after( \"<span class='error' id='posterror'>Post Name is required</span>\" );\r\n");
      out.write("\t\t\t\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$( \"#role_id\" ).after( \"<span class='error' id='roleerror'></span>\" );\r\n");
      out.write("\t\t\t\t\t\t$( \"#post_id\" ).after( \"<span class='error' id='posterror'></span>\" );\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\treturn true;\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t  \r\n");
      out.write("\t      \r\n");
      out.write("\t      function checkMaster(master){\r\n");
      out.write("\t      \t\tvar masterPass = master.value;\r\n");
      out.write("\t      \t\tvar userId = $('#reset_serial_no').val();\r\n");
      out.write("\t\t      \t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:'GET',\r\n");
      out.write("\t\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/createUser/passwordCheck/'+Sha256.hash(masterPass)+'/'+userId+'.htm',\r\n");
      out.write("\t\t\t\t\t beforeSend: function(){\r\n");
      out.write("\t\t\t\t\t\t\t        $('#divLoading').show();\r\n");
      out.write("\t\t\t\t\t\t\t    },\r\n");
      out.write("\t\t\t\t\t\t\tcomplete: function(){\r\n");
      out.write("\t\t\t\t\t\t\t        $('#divLoading').hide();\r\n");
      out.write("\t\t\t\t\t\t\t    },\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(data == \"ok\"){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t$( \"#passCheck\" ).html( \"<span Style='color:green'>Password is valid</span>\" );\r\n");
      out.write("\t\t\t\t\t\t\t\t $(\"#reset_password\").attr(\"readonly\", false);\r\n");
      out.write("\t\t\t\t\t\t\t\t $(\"#re_newpassword\").attr(\"readonly\", false);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t$( \"#passCheck\" ).html( \"<span Style='color: red'>Password is invalid</span>\" );\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#reset_password\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#re_newpassword\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t      }         \t\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  function checkValidate(){\t    \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t \tif($('#re_newpassword').val() != \"\"){\r\n");
      out.write("\t\t\t\t\t$('#reset_password').val(Sha256.hash($('#reset_password').val()));\r\n");
      out.write("\t\t\t\t\t$('#re_newpassword').val(Sha256.hash($('#re_newpassword').val()));\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treturn true;\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/administration/createUser.jsp(79,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/administration/createUser.jsp(79,2) '${listUsers}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listUsers}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/administration/createUser.jsp(79,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("user");
      // /WEB-INF/jsp/administration/createUser.jsp(79,2) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t<tr>\r\n");
            out.write("\t\t\t<td >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_serial_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_login_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\t\t\t\t\t\t\r\n");
            out.write("\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.role_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.post_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\r\n");
            out.write("\r\n");
            out.write("\t\t\t<td><button class=\"btn btn-primary btn-xs disable");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_lock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(" \" \r\n");
            out.write("\t\t\tonclick=\"callEditAjaxRequest(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_serial_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(");\">\r\n");
            out.write("    <span class=\"glyphicon glyphicon-pencil\"></span></button></td>\r\n");
            out.write("    \r\n");
            out.write("    <td style=\"text-align: center; vertical-align: middle;\">\r\n");
            out.write("    \r\n");
            out.write("    <button onclick=\"callDelateRequest(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_serial_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(" , '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_login_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('\'');
            out.write(',');
            out.write('\'');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_lock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("' )\" \r\n");
            out.write("    class=\"btn btn-xs btn-light-blue lock");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_lock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\"  data-title=\"Delete\" data-toggle=\"modal\" data-target=\"#delete\" >\r\n");
            out.write("    <span class=\"glyphicon glyphicon-ban-circle\"></span>\r\n");
            out.write("    </button>\r\n");
            out.write("    \r\n");
            out.write("    </td>\r\n");
            out.write("    \r\n");
            out.write("    \r\n");
            out.write("    <td style=\"text-align: center; vertical-align: middle;\" ><button class=\"btn btn-warning btn-xs disable");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_lock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\" \r\n");
            out.write("\t\t\tonclick=\"callResetRequest(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_serial_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write(" , '");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_login_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("');\">\r\n");
            out.write("    <span class=\"glyphicon glyphicon-wrench\"></span></button></td>\r\n");
            out.write("\t\t</tr>\r\n");
            out.write("\t\t\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/administration/createUser.jsp(120,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("addAction");
      // /WEB-INF/jsp/administration/createUser.jsp(120,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/user/add.htm");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fmethod_005fid_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f0_reused = false;
    try {
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /WEB-INF/jsp/administration/createUser.jsp(121,6) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addAction}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /WEB-INF/jsp/administration/createUser.jsp(121,6) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setCommandName("user");
      // /WEB-INF/jsp/administration/createUser.jsp(121,6) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("post");
      // /WEB-INF/jsp/administration/createUser.jsp(121,6) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setId("formCheckPassword");
      // /WEB-INF/jsp/administration/createUser.jsp(121,6) name = onsubmit type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setOnsubmit("return selectValidate()");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    \t <input type=\"hidden\" id=\"changer\" name=\"changer\">\r\n");
            out.write("    \t <input type=\"hidden\" id=\"serial_no\" name=\"serial_no\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\">\r\n");
            out.write("    \t \r\n");
            out.write("\t  <div class=\"col-md-12 panel panel-white\" >\r\n");
            out.write("\t  <div class=\"col-md-11\" ><BR/><BR/>\r\n");
            out.write("\t  <center>\r\n");
            out.write("\t  <table width=\"60%\" >\r\n");
            out.write("\t\t\t<tr><th>\tRole <span class=\"symbol required\"></span></th>\r\n");
            out.write("\t\t\t<td>\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_form_005fselect_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\t\t\r\n");
            out.write("\t\t\t</td></tr>\r\n");
            out.write("\t\t\t<tr><td> &nbsp;</td></tr>\r\n");
            out.write("\t\t<tr><th>\tPost <span class=\"symbol required\"></span></th>\r\n");
            out.write("\t\t\t<td>\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_form_005fselect_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t</td></tr>\r\n");
            out.write("\t\t\t<tr><td> &nbsp;</td></tr>\r\n");
            out.write("\t\t\t<tr><th>\r\n");
            out.write("\t\t\tFirst Name <span class=\"symbol required\"></span>\r\n");
            out.write("\t\t\t</th>\r\n");
            out.write("\t\t\t<td><input type=\"text\" placeholder=\"Enter First Name\" class=\"form-control only-letters\" id=\"firstname\" name=\"firstname\" ></td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t<tr><td> &nbsp;</td></tr>\r\n");
            out.write("\t\t\t<tr><th>\r\n");
            out.write("\t\t\tUsername <span class=\"symbol required\"></span>\r\n");
            out.write("\t\t\t</th>\r\n");
            out.write("\t\t\t<td><input type=\"text\" placeholder=\"Enter User Name\" class=\"form-control only-letters\" id=\"username\" name=\"username\"></td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t<tr><td> &nbsp;</td></tr>\r\n");
            out.write("\t\t\t<tr class=\"passwordHide\"><th>\r\n");
            out.write("\t\t\tPassword <span class=\"symbol required\"></span>\r\n");
            out.write("\t\t\t</th>\r\n");
            out.write("\t\t\t<td><input type=\"password\" placeholder=\"Enter Password\" class=\"form-control\" id=\"password\" name=\"password\" ></td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t\t<tr><td> &nbsp;</td></tr>\r\n");
            out.write("\t\t\t<tr class=\"passwordHide\"><th>\r\n");
            out.write("\t\t\tConfirm Password <span class=\"symbol required\"></span>\r\n");
            out.write("\t\t\t</th>\r\n");
            out.write("\t\t\t<td><input type=\"password\"  placeholder=\"Re-Enter password\" class=\"form-control\" id=\"password_again\" name=\"password_again\" ></td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t</table>\r\n");
            out.write("\t  </center>\r\n");
            out.write("\t  </div>\r\n");
            out.write("\t  <div class=\"col-md-9 margin-bottom-15\">\r\n");
            out.write("\t  <button class=\"btn  btn-wide btn-azure pull-right margin-top-20 margin-left-20 \" type=\"button\" onclick=\"cancleCreate()\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tCancel <i class=\"glyphicon glyphicon-remove\"></i>\r\n");
            out.write("\t  </button>\r\n");
            out.write("       <button class=\"btn  btn-wide btn-success pull-right margin-top-20 nameChange\" type=\"submit\" id=\"\" >\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tRegister <i class=\"fa fa-arrow-circle-right\"></i>\r\n");
            out.write("\t   </button>\r\n");
            out.write("      </div>\t\r\n");
            out.write("\t  </div>\t\r\n");
            out.write("\t  ");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fmethod_005fid_005fcommandName_005faction.reuse(_jspx_th_form_005fform_005f0);
      _jspx_th_form_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fselect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_form_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fid_005fdata_002dlive_002dsearch_005fclass.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    boolean _jspx_th_form_005fselect_005f0_reused = false;
    try {
      _jspx_th_form_005fselect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/administration/createUser.jsp(131,3) null
      _jspx_th_form_005fselect_005f0.setDynamicAttribute(null, "class", "form-control selectpicker required");
      // /WEB-INF/jsp/administration/createUser.jsp(131,3) null
      _jspx_th_form_005fselect_005f0.setDynamicAttribute(null, "data-live-search", "true");
      // /WEB-INF/jsp/administration/createUser.jsp(131,3) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fselect_005f0.setId("role_id");
      // /WEB-INF/jsp/administration/createUser.jsp(131,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fselect_005f0.setPath("role_id");
      int[] _jspx_push_body_count_form_005fselect_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fselect_005f0 = _jspx_th_form_005fselect_005f0.doStartTag();
        if (_jspx_eval_form_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t <option value='S'>--Select--</option>\r\n");
            out.write("\t\t\t\t\t ");
            if (_jspx_meth_form_005foptions_005f0(_jspx_th_form_005fselect_005f0, _jspx_page_context, _jspx_push_body_count_form_005fselect_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_form_005fselect_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fselect_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fselect_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fselect_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fid_005fdata_002dlive_002dsearch_005fclass.reuse(_jspx_th_form_005fselect_005f0);
      _jspx_th_form_005fselect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fselect_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fselect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005foptions_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fselect_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:options
    org.springframework.web.servlet.tags.form.OptionsTag _jspx_th_form_005foptions_005f0 = (org.springframework.web.servlet.tags.form.OptionsTag) _005fjspx_005ftagPool_005fform_005foptions_0026_005fitems_005fnobody.get(org.springframework.web.servlet.tags.form.OptionsTag.class);
    boolean _jspx_th_form_005foptions_005f0_reused = false;
    try {
      _jspx_th_form_005foptions_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005foptions_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fselect_005f0);
      // /WEB-INF/jsp/administration/createUser.jsp(134,6) name = items type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005foptions_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${RolesList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      int[] _jspx_push_body_count_form_005foptions_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005foptions_005f0 = _jspx_th_form_005foptions_005f0.doStartTag();
        if (_jspx_th_form_005foptions_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005foptions_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005foptions_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005foptions_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005foptions_0026_005fitems_005fnobody.reuse(_jspx_th_form_005foptions_005f0);
      _jspx_th_form_005foptions_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005foptions_005f0, _jsp_getInstanceManager(), _jspx_th_form_005foptions_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fselect_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:select
    org.springframework.web.servlet.tags.form.SelectTag _jspx_th_form_005fselect_005f1 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fid_005fdata_002dlive_002dsearch_005fclass.get(org.springframework.web.servlet.tags.form.SelectTag.class);
    boolean _jspx_th_form_005fselect_005f1_reused = false;
    try {
      _jspx_th_form_005fselect_005f1.setPageContext(_jspx_page_context);
      _jspx_th_form_005fselect_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/jsp/administration/createUser.jsp(140,3) null
      _jspx_th_form_005fselect_005f1.setDynamicAttribute(null, "class", "form-control selectpicker required");
      // /WEB-INF/jsp/administration/createUser.jsp(140,3) null
      _jspx_th_form_005fselect_005f1.setDynamicAttribute(null, "data-live-search", "true");
      // /WEB-INF/jsp/administration/createUser.jsp(140,3) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fselect_005f1.setId("post_id");
      // /WEB-INF/jsp/administration/createUser.jsp(140,3) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fselect_005f1.setPath("post_id");
      int[] _jspx_push_body_count_form_005fselect_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fselect_005f1 = _jspx_th_form_005fselect_005f1.doStartTag();
        if (_jspx_eval_form_005fselect_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t <option value='S'>--Select--</option>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_form_005fselect_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fselect_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fselect_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fselect_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fselect_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fid_005fdata_002dlive_002dsearch_005fclass.reuse(_jspx_th_form_005fselect_005f1);
      _jspx_th_form_005fselect_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fselect_005f1, _jsp_getInstanceManager(), _jspx_th_form_005fselect_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/jsp/administration/createUser.jsp(213,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setVar("addAction");
      // /WEB-INF/jsp/administration/createUser.jsp(213,2) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/createUsers/resetPassword.htm");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fform_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f1 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fmethod_005fid_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_form_005fform_005f1_reused = false;
    try {
      _jspx_th_form_005fform_005f1.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f1.setParent(null);
      // /WEB-INF/jsp/administration/createUser.jsp(214,6) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f1.setAction((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${addAction}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      // /WEB-INF/jsp/administration/createUser.jsp(214,6) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f1.setCommandName("user");
      // /WEB-INF/jsp/administration/createUser.jsp(214,6) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f1.setMethod("post");
      // /WEB-INF/jsp/administration/createUser.jsp(214,6) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f1.setId("formCheck");
      // /WEB-INF/jsp/administration/createUser.jsp(214,6) name = onsubmit type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f1.setOnsubmit("return checkValidate()");
      int[] _jspx_push_body_count_form_005fform_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f1 = _jspx_th_form_005fform_005f1.doStartTag();
        if (_jspx_eval_form_005fform_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    \t <input type=\"hidden\" id=\"reset_serial_no\" name=\"serial_no\" >\r\n");
            out.write("\t\t  <div class=\"col-md-12 panel panel-white\" >\r\n");
            out.write("\t\t  <div class=\"col-md-11\" ><BR/><BR/>\r\n");
            out.write("\t\t  <center>\r\n");
            out.write("\t\t  <table width=\"60%\" >\r\n");
            out.write("\t\t\t<tr ><th>\r\n");
            out.write("\t\t\tName of User \r\n");
            out.write("\t\t\t</th>\r\n");
            out.write("\t\t\t<td ><span id=\"resetUserName\"></span></td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t<tr><td> &nbsp;</td></tr>\r\n");
            out.write("\t\t\t<tr ><th>\r\n");
            out.write("\t\t\tOld Password / Master Password<span class=\"symbol required\"></span>\r\n");
            out.write("\t\t\t</th>\r\n");
            out.write("\t\t\t<td><input type=\"password\" onchange=\"checkMaster(this);\" placeholder=\"Enter Old Password\" class=\"form-control\" \r\n");
            out.write("\t\t\tid=\"master_password\" name=\"master_password\">\r\n");
            out.write("\t\t\t<span id=\"passCheck\"></span>\r\n");
            out.write("\t\t\t</td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t<tr><td> &nbsp;</td></tr><tr><td> &nbsp;</td></tr>\r\n");
            out.write("\t\t\t<tr ><th>\r\n");
            out.write("\t\t\tNew Password <span class=\"symbol required\"></span>\r\n");
            out.write("\t\t\t</th>\r\n");
            out.write("\t\t\t<td><input type=\"password\" placeholder=\"Enter New Password\" readonly title=\"First Enter Old Password/ Master Password\"\r\n");
            out.write("\t\t\tclass=\"form-control\" id=\"reset_password\" name=\"reset_password\"></td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t\t\t\t<tr><td> &nbsp;</td></tr>\r\n");
            out.write("\t\t\t<tr ><th>\r\n");
            out.write("\t\t\tConfirm Password <span class=\"symbol required\"></span>\r\n");
            out.write("\t\t\t</th>\r\n");
            out.write("\t\t\t<td><input type=\"password\"  placeholder=\"Re-Enter New password\" class=\"form-control\" readonly id=\"re_newpassword\" name=\"re_newpassword\"></td>\r\n");
            out.write("\t\t\t</tr>\r\n");
            out.write("\t</table>\r\n");
            out.write("\t  </center>\r\n");
            out.write("\t  </div>\r\n");
            out.write("\t  <div class=\"col-md-9 margin-bottom-15\">\r\n");
            out.write("\t  <button class=\"btn  btn-wide btn-azure pull-right margin-top-20 margin-left-20 \" type=\"button\" onclick=\"cancleCreate()\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tCancel <i class=\"glyphicon glyphicon-remove\"></i>\r\n");
            out.write("\t  </button>\r\n");
            out.write("      <button  class=\"btn  btn-wide btn-success pull-right margin-top-20 nameChange\"   type=\"submit\" >\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tReset <i class=\"fa fa-arrow-circle-right\"></i>\r\n");
            out.write("\t   </button>\r\n");
            out.write("      </div>\t\r\n");
            out.write("\t  </div>\t\r\n");
            out.write("\t  ");
            int evalDoAfterBody = _jspx_th_form_005fform_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fmethod_005fid_005fcommandName_005faction.reuse(_jspx_th_form_005fform_005f1);
      _jspx_th_form_005fform_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f1, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f1_reused);
    }
    return false;
  }
}
