/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2018-03-30 04:48:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.reports;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class regMemProgressiveReport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<!--<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t\t-->\r\n");
      out.write("\t\t<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("\t\t<!--\r\n");
      out.write("\t\t <meta charset=\"UTF-8\">\r\n");
      out.write("\t\t-->\r\n");
      out.write("\t\t<link\r\n");
      out.write("\t\t\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" />\r\n");
      out.write("\t\t<link\r\n");
      out.write("\t\t\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" />\r\n");
      out.write("\t\t<script\r\n");
      out.write("\t\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t\t<!-- start: MAIN CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\"\r\n");
      out.write("\t\t\thref=\"vendor/fontawesome/css/font-awesome.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\"\r\n");
      out.write("\t\t\thref=\"vendor/themify-icons/themify-icons.min.css\">\r\n");
      out.write("\t\t<link href=\"vendor/animate.css/animate.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\t\t\tmedia=\"screen\">\r\n");
      out.write("\t\t<link href=\"vendor/perfect-scrollbar/perfect-scrollbar.min.css\"\r\n");
      out.write("\t\t\trel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("\t\t<link href=\"vendor/switchery/switchery.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\t\t\tmedia=\"screen\">\r\n");
      out.write("\t\t<!-- end: MAIN CSS -->\r\n");
      out.write("\t\t<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->\r\n");
      out.write("\t\t<link\r\n");
      out.write("\t\t\thref=\"vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.css\"\r\n");
      out.write("\t\t\trel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("\t\t<link href=\"vendor/select2/select2.min.css\" rel=\"stylesheet\"\r\n");
      out.write("\t\t\tmedia=\"screen\">\r\n");
      out.write("\t\t<link\r\n");
      out.write("\t\t\thref=\"vendor/bootstrap-datepicker/bootstrap-datepicker3.standalone.min.css\"\r\n");
      out.write("\t\t\trel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("\t\t<link href=\"vendor/bootstrap-timepicker/bootstrap-timepicker.min.css\"\r\n");
      out.write("\t\t\trel=\"stylesheet\" media=\"screen\">\r\n");
      out.write("\t\t<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->\r\n");
      out.write("\t\t<!-- start: CLIP-TWO CSS -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/css/styles.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/css/plugins.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/css/themes/theme-1.css\"\r\n");
      out.write("\t\t\tid=\"skin_color\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\"\r\n");
      out.write("\t\t\thref=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/css/bootstrap-select.min.css\">\r\n");
      out.write("\t\t<!-- end: CLIP-TWO CSS -->\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t<div id=\"link\" style=\"float:right;margin-bottom:10px;margin-right:20px\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-hover\" id=\"district_table\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tSNO\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tDISTRICT\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tTOTAL REGISTERED MEMBERS\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"table-responsive\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-hover\" id=\"assembly_table\"\r\n");
      out.write("\t\t\t\tstyle=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tSNO\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tASSEMBLY\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tTOTAL REGISTERED MEMBERS\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody id=\"assembly_table_body\"></tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"table-responsive\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-hover\" id=\"mandal_table\"\r\n");
      out.write("\t\t\t\tstyle=\"display: none\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tSNO\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tMANDAL\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tTOTAL REGISTERED MEMBERS\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody id=\"mandal_table_body\"></tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-hover\" id=\"panchayati_table\"\r\n");
      out.write("\t\t\t\tstyle=\"display: none\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tSNO\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tPANCHAYATI\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tTOTAL REGISTERED MEMBERS\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody id=\"panchayati_table_body\"></tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-hover\"\r\n");
      out.write("\t\t\t\tid=\"polingstation_table\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tSNO\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tPOLINGSTATION\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tTOTAL REGISTERED MEMBERS\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tTOTAL REGISTERED MEMBERS\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody id=\"polingstation_table_body\"></tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"table-responsive\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-hover\"\r\n");
      out.write("\t\t\t\tid=\"polingstation_details_table\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tSNO\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tMEMBER NAME\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tMOBILE NUMBER\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t\t\tEMAIL ID\r\n");
      out.write("\t\t\t\t\t\t</th>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody id=\"polingstation_details_table_body\"></tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->\r\n");
      out.write("\t<script src=\"vendor/maskedinput/jquery.maskedinput.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"vendor/bootstrap-touchspin/jquery.bootstrap-touchspin.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t<script src=\"vendor/autosize/autosize.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t<script src=\"vendor/selectFx/classie.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t<script src=\"vendor/selectFx/selectFx.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t<script src=\"vendor/select2/select2.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t<script src=\"vendor/bootstrap-datepicker/bootstrap-datepicker.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t<script src=\"vendor/bootstrap-timepicker/bootstrap-timepicker.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->\r\n");
      out.write("\t<!-- start: CLIP-TWO JAVASCRIPTS -->\r\n");
      out.write("\t<script src=\"assets/js/main.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.7.5/js/bootstrap-select.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t<!-- start: JavaScript Event Handlers for this page -->\r\n");
      out.write("\t<script src=\"assets/js/form-elements.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"resources/js/drilldownReport.js\">\r\n");
      out.write("</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("function backNavigation(location) {\r\n");
      out.write("\talert(location);\r\n");
      out.write("\tif (location == 1) {\r\n");
      out.write("\t\t$('#district_table').show();\r\n");
      out.write("\t\t$('#assembly_table').hide();\r\n");
      out.write("\t\t$('#mandal_table').hide();\r\n");
      out.write("\t\t$('#panchayati_table').hide();\r\n");
      out.write("\t\t$('#polingstation_table').hide();\r\n");
      out.write("\t\t$('#polingstation_details_table').hide();\r\n");
      out.write("\t\t$('#link').html(\"\");\r\n");
      out.write("\t} else if (location == 2) {\r\n");
      out.write("\t\r\n");
      out.write("\t\t$('#district_table').hide();\r\n");
      out.write("\t\t$('#assembly_table').show();\r\n");
      out.write("\t\t$('#mandal_table').hide();\r\n");
      out.write("\t\t$('#panchayati_table').hide();\r\n");
      out.write("\t\t$('#polingstation_table').hide();\r\n");
      out.write("\t\t$('#polingstation_details_table').hide();\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar navi = \"<a onclick='backNavigation(1)'>Back to District</a>\";\r\n");
      out.write("\t\t$('#link').html(navi);\r\n");
      out.write("\t} else if (location == 3) {\r\n");
      out.write("\t\t$('#district_table').hide();\r\n");
      out.write("\t\t$('#assembly_table').hide();\r\n");
      out.write("\t\t$('#mandal_table').show();\r\n");
      out.write("\t\t$('#panchayati_table').hide();\r\n");
      out.write("\t\t$('#polingstation_table').hide();\r\n");
      out.write("\t\t$('#polingstation_details_table').hide();\r\n");
      out.write("\r\n");
      out.write("\t\tvar navi = \"<a onclick='backNavigation(2)'>Back to AssemblyWise</a> &nbsp; <a onclick='backNavigation(1)'>Back to District</a>\";\r\n");
      out.write("\t\t$('#link').html(navi);\r\n");
      out.write("\t}else if (location == 4) {\r\n");
      out.write("\r\n");
      out.write("\t\t$('#district_table').hide();\r\n");
      out.write("\t\t$('#assembly_table').hide();\r\n");
      out.write("\t\t$('#mandal_table').hide();\r\n");
      out.write("\t\t$('#panchayati_table').show();\r\n");
      out.write("\t\t$('#polingstation_table').hide();\r\n");
      out.write("\t\t$('#polingstation_details_table').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar navi = \"<a onclick='backNavigation(3)'>Back to MandalWise</a> &nbsp; <a onclick='backNavigation(2)'>Back to AssemblyWise</a> &nbsp; <a onclick='backNavigation(1)'>Back to District</a>\";\r\n");
      out.write("\t\t$('#link').html(navi);\r\n");
      out.write("\t}else if (location == 5) {\r\n");
      out.write("\t\t$('#district_table').hide();\r\n");
      out.write("\t\t$('#assembly_table').hide();\r\n");
      out.write("\t\t$('#mandal_table').hide();\r\n");
      out.write("\t\t$('#panchayati_table').hide();\r\n");
      out.write("\t\t$('#polingstation_table').show();\r\n");
      out.write("\t\t$('#polingstation_details_table').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar navi = \"<a onclick='backNavigation(4)'>Back to PanchayatiWise</a> &nbsp; <a onclick='backNavigation(3)'>Back to MandalWise</a> &nbsp; <a onclick='backNavigation(2)'>Back to AssemblyWise</a> &nbsp; <a onclick='backNavigation(1)'>Back to District</a>\";\r\n");
      out.write("\t$('#link').html(navi);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function getAssemblyWise(districtId) {\r\n");
      out.write("\r\n");
      out.write("\tvar navi = \"<a onclick='backNavigation(1)'>Back to District</a>\";\r\n");
      out.write("\t$('#link').html(navi);\r\n");
      out.write("\r\n");
      out.write("\tvar link = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/getAssemblyWise/' + districtId + '.htm';\r\n");
      out.write("\t\t$(\"#assembly_table_body\").empty();\r\n");
      out.write("\t$.get(link, function(data) {\r\n");
      out.write("\t\r\n");
      out.write("\t\t$('#district_table').hide();\r\n");
      out.write("\t\t$('#assembly_table').show();\r\n");
      out.write("\r\n");
      out.write("\t\tvar output = JSON.parse(data);\r\n");
      out.write("\t\tconsole.log(output);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.each(output, function(index, value) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar row = $(\"<tr><td>\" + value.SRNO\r\n");
      out.write("\t\t\t\t\t+ \"</td><td onClick='getMandalWise(\" + value.ASSEMBLY_CODE\r\n");
      out.write("\t\t\t\t\t+ \")'><a>\" + value.ASSEMBLY_NAME + \"</a></td><td>\"\r\n");
      out.write("\t\t\t\t\t+ value.COUNTER + \"</td></tr>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t$(\"#assembly_table\").append(row);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getMandalWise(assemblyId) {\r\n");
      out.write("\tvar navi = \"<a onclick='backNavigation(2)'>Back to AssemblyWise</a> &nbsp; <a onclick='backNavigation(1)'>Back to District</a>\";\r\n");
      out.write("\t$('#link').html(navi);\r\n");
      out.write("\t\r\n");
      out.write("\tvar link = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/getMandalWise/' + assemblyId + '.htm';\r\n");
      out.write("$(\"#mandal_table_body\").empty();\r\n");
      out.write("\t$.get(link, function(data) {\r\n");
      out.write("\t\t$('#assembly_table').hide();\r\n");
      out.write("\t\t$('#mandal_table').show();\r\n");
      out.write("\t\tvar output = JSON.parse(data);\r\n");
      out.write("\t\tconsole.log(output);\r\n");
      out.write("\t\t$.each(output, function(index, value) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar row = $(\"<tr><td>\" + value.SRNO\r\n");
      out.write("\t\t\t\t\t+ \"</td><td onClick='getPanchayatiWise(\"\r\n");
      out.write("\t\t\t\t\t+ value.MANDAL_CODE + \")'><a  >\" + value.MANDAL_NAME\r\n");
      out.write("\t\t\t\t\t+ \"</a></td><td>\" + value.COUNTER + \"</td></tr>\");\r\n");
      out.write("\t\t\t$(\"#mandal_table\").append(row);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getPanchayatiWise(mandalId) {\r\n");
      out.write("\tvar navi = \"<a onclick='backNavigation(3)'>Back to MandalWise</a> &nbsp; <a onclick='backNavigation(2)'>Back to AssemblyWise</a> &nbsp; <a onclick='backNavigation(1)'>Back to District</a>\";\r\n");
      out.write("\t$('#link').html(navi);\r\n");
      out.write("\r\n");
      out.write("\tvar link = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/getPanchayatiWise/' + mandalId + '.htm';\r\n");
      out.write("\t$(\"#panchayati_table_body\").empty();\r\n");
      out.write("\t\r\n");
      out.write("\t$.get(link, function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t$('#mandal_table').hide();\r\n");
      out.write("\t\t$('#panchayati_table').show();\r\n");
      out.write("\r\n");
      out.write("\t\tvar output = JSON.parse(data);\r\n");
      out.write("\t\tconsole.log(output);\r\n");
      out.write("\t\t$.each(output, function(index, value) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar row = $(\"<tr><td>\" + value.SRNO\r\n");
      out.write("\t\t\t\t\t+ \"</td><td onClick='getPolingStationWise(\"\r\n");
      out.write("\t\t\t\t\t+ value.PANCHAYATI_CODE + \")'><a  >\"\r\n");
      out.write("\t\t\t\t\t+ value.PANCHAYATI_NAME + \"</a></td><td>\" + value.COUNTER\r\n");
      out.write("\t\t\t\t\t+ \"</td></tr>\");\r\n");
      out.write("\t\t\t$(\"#panchayati_table\").append(row);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getPolingStationWise(panchayatiId) {\r\n");
      out.write("\tvar navi = \"<a onclick='backNavigation(4)'>Back to PanchayatiWise</a> &nbsp; <a onclick='backNavigation(3)'>Back to MandalWise</a> &nbsp; <a onclick='backNavigation(2)'>Back to AssemblyWise</a> &nbsp; <a onclick='backNavigation(1)'>Back to District</a>\";\r\n");
      out.write("\t$('#link').html(navi);\r\n");
      out.write("\r\n");
      out.write("\tvar link = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/getPolingStationWise/' + panchayatiId + '.htm';\r\n");
      out.write("\t$(\"#polingstation_table_body\").empty();\r\n");
      out.write("\t\r\n");
      out.write("\t$.get(link, function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t$('#panchayati_table').hide();\r\n");
      out.write("\t\t$('#polingstation_table').show();\r\n");
      out.write("\r\n");
      out.write("\t\tvar output = JSON.parse(data);\r\n");
      out.write("\t\tconsole.log(output);\r\n");
      out.write("\t\t$.each(output, function(index, value) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar row = $(\"<tr><td>\" + value.SRNO + \"</td><td onClick=''>\"\r\n");
      out.write("\t\t\t\t\t+ value.POLINGSTATION_NAME + \"</td><td>\" + value.COUNTER\r\n");
      out.write("\t\t\t\t\t+ \"</td><td onClick='getPolingStationWiseDetails(\"\r\n");
      out.write("\t\t\t\t\t+ value.POLINGSTATION_CODE + \")'><a>View</a></td></tr>\");\r\n");
      out.write("\t\t\t$(\"#polingstation_table\").append(row);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getPolingStationWiseDetails(polingStationId) {\r\n");
      out.write("\tvar navi = \"<a onclick='backNavigation(5)'>Back to PolingStationWise</a> &nbsp; <a onclick='backNavigation(4)'>Back to PanchayatiWise</a> &nbsp; <a onclick='backNavigation(3)'>Back to MandalWise</a> &nbsp; <a onclick='backNavigation(2)'>Back to AssemblyWise</a> &nbsp; <a onclick='backNavigation(1)'>Back to District</a>\";\r\n");
      out.write("\t$('#link').html(navi);\r\n");
      out.write("\t\r\n");
      out.write("\tvar link = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/getPolingStationWiseDetails/' + polingStationId + '.htm';\r\n");
      out.write("\t$(\"#polingstation_details_table_body\").empty();\r\n");
      out.write("\t\r\n");
      out.write("\t$.get(link, function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t$('#polingstation_table').hide();\r\n");
      out.write("\t\t$('#polingstation_details_table').show();\r\n");
      out.write("\r\n");
      out.write("\t\tvar output = JSON.parse(data);\r\n");
      out.write("\t\tconsole.log(output);\r\n");
      out.write("\t\t$.each(output, function(index, value) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar row = $(\"<tr><td>\" + value.SRNO + \"</td><td>\"\r\n");
      out.write("\t\t\t\t\t+ value.MEMBER_NAME + \"</td><td>\" + value.MOBILE_NUMBER\r\n");
      out.write("\t\t\t\t\t+ \"</td><td>\" + value.EMAIL_ID + \"</td></tr>\");\r\n");
      out.write("\t\t\t$(\"#polingstation_details_table\").append(row);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/reports/regMemProgressiveReport.jsp(84,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("reg");
      // /WEB-INF/jsp/reports/regMemProgressiveReport.jsp(84,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/reports/regMemProgressiveReport.jsp(84,5) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reg.sno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<a href=\"\" onClick=\"getAssemblyWise('");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reg.districtCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("')\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reg.district}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</a>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reg.totalRegisteredMembers}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
