/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2018-03-29 05:00:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div ng-controller=\"servicesController\">\r\n");
      out.write("\t<!-- sidebar -->\r\n");
      out.write("\t<div class=\"sidebar app-aside\" id=\"sidebar\">\r\n");
      out.write("\t\t<div class=\"sidebar-container perfect-scrollbar\">\r\n");
      out.write("\t\t\t<nav>\r\n");
      out.write("\t\t\t<!-- start: SEARCH FORM -->\r\n");
      out.write("\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t<a class=\"s-open\" href=\"#\"> <i class=\"ti-search\"></i> </a>\r\n");
      out.write("\t\t\t\t<form class=\"navbar-form\" role=\"search\">\r\n");
      out.write("\t\t\t\t\t<a class=\"s-remove\" href=\"#\" target=\".navbar-form\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"ti-close\"></i> </a>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn search-button\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"ti-search\"></i>\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end: SEARCH FORM -->\r\n");
      out.write("\t\t\t<!-- start: MAIN NAVIGATION MENU -->\r\n");
      out.write("\t\t\t<div class=\"navbar-title\">\r\n");
      out.write("\t\t\t\t<span>Main Navigation</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"main-navigation-menu\">\r\n");
      out.write("\t\t\t\t<li class=\"active open\">\r\n");
      out.write("\t\t\t\t\t<a href=\"welcome.htm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"\">&emsp;&emsp;&emsp;</i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title\"> Dashboard </span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"ti-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title\"> User Profile </span><i class=\"icon-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"editProfile.htm\"> <span class=\"title\"> Edit\r\n");
      out.write("\t\t\t\t\t\t\t\t\tProfile </span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!--Only Admin -->\r\n");
      out.write("\t\t\t\t");

					Object name = request.getSession().getAttribute("DISPLAY_NAME");
					boolean check = name.equals("Developer");
				
      out.write("\r\n");
      out.write("\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /WEB-INF/jsp/common/menu.jsp(62,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(check);
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<li>\r\n");
            out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\">\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"item-content\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<i class=\"ti-settings\"></i>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<span class=\"title\"> Administration </span><i\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\tclass=\"icon-arrow\"></i>\r\n");
            out.write("\t\t\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t</div> </a>\r\n");
            out.write("\t\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
            out.write("\t\t\t\t\t\t\t<li>\r\n");
            out.write("\t\t\t\t\t\t\t\t<a href=\"createUser.htm\"> <span class=\"title\"> Create\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\tUser </span> </a>\r\n");
            out.write("\t\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t\t\t<li>\r\n");
            out.write("\t\t\t\t\t\t\t\t<a href=\"createRole.htm\"> <span class=\"title\"> Create\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\tRole </span> </a>\r\n");
            out.write("\t\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t\t\t<li>\r\n");
            out.write("\t\t\t\t\t\t\t\t<a href=\"createService.htm\"> <span class=\"title\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\tCreate Service </span> </a>\r\n");
            out.write("\t\t\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t\t\t<li>\r\n");
            out.write("\t\t\t\t\t\t\t\t<a href=\"mapServices.htm\"> <span class=\"title\"> Map\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\tServices </span> </a>\r\n");
            out.write("\t\t\t\t\t\t\t</li>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t</ul>\r\n");
            out.write("\t\t\t\t\t</li>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t\t<!--end only Admin -->\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"ti-write\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title\"> News </span><i class=\"icon-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"latestnews.htm\"> <span class=\"title\">Latest\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNews</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"entertainment.htm\"> <span class=\"title\">Entertainment</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"sports.htm\"> <span class=\"title\">Sports</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"business.htm\"> <span class=\"title\">Business</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"eduemp.htm\"> <span class=\"title\">Education/Employment</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"family.htm\"> <span class=\"title\">Family/Health</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"ti-video-camera\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title\"> Videos </span><i class=\"icon-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"videos.htm\"> <span class=\"title\">Videos Data</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"ti-layers-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title\"> Politician Profiles </span><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"icon-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"mla.htm\"> <span class=\"title\">MLA</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"mp.htm\"> <span class=\"title\">MP</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"mlc.htm\"> <span class=\"title\">MLC</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"zptc.htm\"> <span class=\"title\">ZPTC</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"corporation.htm\"> <span class=\"title\">Corporation</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"dccb.htm\"> <span class=\"title\">DCCB</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"ti-package\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title\"> Party Committees </span><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"icon-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"pcc.htm\"> <span class=\"title\">PCC Committee</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"womens.htm\"> <span class=\"title\">Womens\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCommittee</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"youth.htm\"> <span class=\"title\">Youth\r\n");
      out.write("\t\t\t\t\t\t\t\t\tCommittee</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"nsui.htm\"> <span class=\"title\">NSUI</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"ti-files\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title\"> Reports</span><i class=\"icon-arrow\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"sub-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"regMemProgressiveReport.htm\"> <span class=\"title\">Registered\r\n");
      out.write("\t\t\t\t\t\t\t\t\tMembers Progressive Report</span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"publishedNewsReport.htm\"> <span class=\"title\">Published News \r\n");
      out.write("\t\t\t\t\t\t\t\t\t </span> </a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"survey.htm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"ti-info-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\"> Survey </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"classifieds.htm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"ti-pie-chart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"title\"> Classifieds </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>-->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- end: MAIN NAVIGATION MENU -->\r\n");
      out.write("\t\t\t<!-- start: CORE FEATURES -->\r\n");
      out.write("\t\t\t<div class=\"navbar-title\">\r\n");
      out.write("\t\t\t\t<span>Other Features</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"folders\">\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"survey.htm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa-stack\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-square fa-stack-2x\"></i> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa  fa-rss fa-stack-1x fa-inverse\"></i> </span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title\"> Survey </span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"classifieds.htm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-media\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa-stack\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-square fa-stack-2x\"></i> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"fa fa-newspaper-o fa-stack-1x fa-inverse\"></i> </span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item-inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"title\"> Classifieds </span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div> </a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- end: CORE FEATURES -->\r\n");
      out.write("\t\t\t<!-- start: DOCUMENTATION BUTTON -->\r\n");
      out.write("\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\t<a href=\"statistics.htm\" class=\"button-o\"> <i\r\n");
      out.write("\t\t\t\t\tclass=\"ti-stats-up\"></i> <span> Statistics</span> </a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end: DOCUMENTATION BUTTON -->\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- / sidebar -->\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("var app = angular.module('mainApp', []);\r\n");
      out.write("app.controller('servicesController', function ($scope) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t $scope.services = ");
      out.print(request.getSession().getAttribute("services"));
      out.write(";\t\r\n");
      out.write("\t\t\t\t\t \t            \r\n");
      out.write("\t\t}); \r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tfunction getMenu(id) {\r\n");
      out.write("\t\t\tvar parent_Id= id.getAttribute(\"data-filterListId\");\r\n");
      out.write("\t\t\tif ( $('#'+parent_Id+'  li').size() > 0 ) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\tvar role_Id=");
      out.print(request.getSession().getAttribute("role_Id"));
      out.write(";\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'GET',\r\n");
      out.write("\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajaxController/menu/'+parent_Id+'/'+role_Id+'.htm',\r\n");
      out.write("\t\t\t\tdataType:'json',\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t$('#'+parent_Id).html( data); \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction getSubMenu(parent_Id, role_Id) {\r\n");
      out.write("\tif ( $('#'+parent_Id+'  li').size() > 0 ) {\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'GET',\r\n");
      out.write("\t\t\t\turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/ajaxController/subMenu/'+parent_Id+'/'+role_Id+'.htm',\r\n");
      out.write("\t\t\t\tdataType:'json',\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t$('#'+parent_Id).html( data); \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- start: JavaScript Event Handlers for this page -->\r\n");
      out.write("<!--<script src=\"assets/js/index.js\"></script>\r\n");
      out.write("\t\t-->\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(document).ready(function() {\r\n");
      out.write("\tMain.init();\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- end: JavaScript Event Handlers for this page -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
