/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.78
 * Generated at: 2018-03-29 05:00:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class settings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- start: SETTINGS -->\r\n");
      out.write("\t\t\t<div class=\"settings panel panel-default hidden-xs hidden-sm\" id=\"settings\">\r\n");
      out.write("\t\t\t\t<button ct-toggle=\"toggle\" data-toggle-class=\"active\" data-toggle-target=\"#settings\" class=\"btn btn-default\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-spin fa-gear\"></i>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\tStyle Selector\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<!-- start: FIXED HEADER -->\r\n");
      out.write("\t\t\t\t\t<div class=\"setting-box clearfix\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"setting-title pull-left\"> Fixed header</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"setting-switch pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"js-switch\" id=\"fixed-header\" />\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- end: FIXED HEADER -->\r\n");
      out.write("\t\t\t\t\t<!-- start: FIXED SIDEBAR -->\r\n");
      out.write("\t\t\t\t\t<div class=\"setting-box clearfix\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"setting-title pull-left\">Fixed sidebar</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"setting-switch pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"js-switch\" id=\"fixed-sidebar\" />\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- end: FIXED SIDEBAR -->\r\n");
      out.write("\t\t\t\t\t<!-- start: CLOSED SIDEBAR -->\r\n");
      out.write("\t\t\t\t\t<div class=\"setting-box clearfix\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"setting-title pull-left\">Closed sidebar</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"setting-switch pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"js-switch\" id=\"closed-sidebar\" />\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- end: CLOSED SIDEBAR -->\r\n");
      out.write("\t\t\t\t\t<!-- start: FIXED FOOTER -->\r\n");
      out.write("\t\t\t\t\t<div class=\"setting-box clearfix\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"setting-title pull-left\">Fixed footer</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"setting-switch pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"js-switch\" id=\"fixed-footer\" />\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- end: FIXED FOOTER -->\r\n");
      out.write("\t\t\t\t\t<!-- start: THEME SWITCHER -->\r\n");
      out.write("\t\t\t\t\t<div class=\"colors-row setting-box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"color-theme theme-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"color-layout\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"setting-theme\" value=\"theme-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"ti-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split header\"> <span class=\"color th-header\"></span> <span class=\"color th-collapse\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split\"> <span class=\"color th-sidebar\"><i class=\"element\"></i></span> <span class=\"color th-body\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"color-theme theme-2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"color-layout\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"setting-theme\" value=\"theme-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"ti-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split header\"> <span class=\"color th-header\"></span> <span class=\"color th-collapse\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split\"> <span class=\"color th-sidebar\"><i class=\"element\"></i></span> <span class=\"color th-body\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"colors-row setting-box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"color-theme theme-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"color-layout\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"setting-theme\" value=\"theme-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"ti-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split header\"> <span class=\"color th-header\"></span> <span class=\"color th-collapse\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split\"> <span class=\"color th-sidebar\"><i class=\"element\"></i></span> <span class=\"color th-body\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"color-theme theme-4\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"color-layout\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"setting-theme\" value=\"theme-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"ti-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split header\"> <span class=\"color th-header\"></span> <span class=\"color th-collapse\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split\"> <span class=\"color th-sidebar\"><i class=\"element\"></i></span> <span class=\"color th-body\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"colors-row setting-box\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"color-theme theme-5\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"color-layout\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"setting-theme\" value=\"theme-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"ti-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split header\"> <span class=\"color th-header\"></span> <span class=\"color th-collapse\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split\"> <span class=\"color th-sidebar\"><i class=\"element\"></i></span> <span class=\"color th-body\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"color-theme theme-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"color-layout\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"setting-theme\" value=\"theme-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"ti-check\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split header\"> <span class=\"color th-header\"></span> <span class=\"color th-collapse\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"split\"> <span class=\"color th-sidebar\"><i class=\"element\"></i></span> <span class=\"color th-body\"></span> </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- end: THEME SWITCHER -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end: SETTINGS -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
